const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

async function main() {

  // ─── Users ──────────────────────────────────────────────────────────────────
  console.log('🌱 Seeding users...')

  const adminPassword = await bcrypt.hash('admin123', 12)
  const memberPassword = await bcrypt.hash('user123', 12)

  const admin = await prisma.user.upsert({
    where: { email: 'admin@gharkhana.com' },
    update: {},
    create: {
      email: 'admin@gharkhana.com',
      name: 'Super Admin',
      passwordHash: adminPassword,
      role: 'SUPER_ADMIN',
      emailVerified: new Date(),
      onboardedAt: new Date(),
      dietaryType: 'BOTH',
      spiceTolerance: 'HOT',
      healthGoal: 'BALANCED',
    }
  })

  const member = await prisma.user.upsert({
    where: { email: 'test@gharkhana.com' },
    update: {},
    create: {
      email: 'test@gharkhana.com',
      name: 'Test User',
      passwordHash: memberPassword,
      role: 'MEMBER',
      emailVerified: new Date(),
      onboardedAt: new Date(),
      dietaryType: 'NON_VEG',
      spiceTolerance: 'MEDIUM',
      healthGoal: 'BALANCED',
    }
  })

  console.log('✅ Users seeded:', admin.email, member.email)

  // ─── Dishes ─────────────────────────────────────────────────────────────────
  console.log('🌱 Seeding dishes...')

  const dishes = [

    // ── Roti-Based | Non-Veg ──────────────────────────────────────────────────
    {
      name: 'Chicken Karahi',
      nameUrdu: 'چکن کڑاہی',
      description: 'Juicy chicken cooked in a spiced tomato and ginger sauce in a wok',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Mutton Karahi',
      nameUrdu: 'مٹن کڑاہی',
      description: 'Slow cooked mutton in a rich spiced karahi gravy',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Beef Qeema',
      nameUrdu: 'بیف قیمہ',
      description: 'Spiced minced beef cooked with peas and tomatoes',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 30,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Handi',
      nameUrdu: 'چکن ہانڈی',
      description: 'Creamy chicken curry cooked in a clay pot style',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 50,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Saag Gosht',
      nameUrdu: 'ساگ گوشت',
      description: 'Tender mutton cooked with fresh spinach and spices',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 75,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Fish Curry',
      nameUrdu: 'مچھلی کری',
      description: 'Fresh fish cooked in a tangy tamarind and spice gravy',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'FISH',
      spiceLevel: 'HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Aloo Gosht',
      nameUrdu: 'آلو گوشت',
      description: 'Mutton and potato curry — a Pakistani household classic',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 80,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Roti-Based | Veg ──────────────────────────────────────────────────────
    {
      name: 'Daal Makhani',
      nameUrdu: 'دال مکھنی',
      description: 'Slow cooked black lentils in a rich buttery sauce',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Aloo Paratha',
      nameUrdu: 'آلو پراٹھا',
      description: 'Crispy flatbread stuffed with spiced mashed potato',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['BREAKFAST', 'LUNCH'],
    },
    {
      name: 'Paneer Karahi',
      nameUrdu: 'پنیر کڑاہی',
      description: 'Cottage cheese cooked in a spiced tomato karahi sauce',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'PANEER',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 35,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Saag',
      nameUrdu: 'ساگ',
      description: 'Slow cooked mustard greens with butter and makki roti',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Rice-Based | Non-Veg ──────────────────────────────────────────────────
    {
      name: 'Chicken Biryani',
      nameUrdu: 'چکن بریانی',
      description: 'Fragrant basmati rice layered with spiced chicken and saffron',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Mutton Biryani',
      nameUrdu: 'مٹن بریانی',
      description: 'Slow dum-cooked mutton biryani with whole spices',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 120,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Beef Pulao',
      nameUrdu: 'بیف پلاؤ',
      description: 'Fragrant rice cooked with tender beef and whole spices',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Pulao',
      nameUrdu: 'چکن پلاؤ',
      description: 'Light and aromatic rice cooked with chicken and subtle spices',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Egg Fried Rice',
      nameUrdu: 'انڈہ فرائیڈ رائس',
      description: 'Stir fried rice with eggs, vegetables and soy sauce',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'EGG',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Fish Biryani',
      nameUrdu: 'مچھلی بریانی',
      description: 'Tangy and spiced fish layered with aromatic basmati rice',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'FISH',
      spiceLevel: 'HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 75,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Rice-Based | Veg ──────────────────────────────────────────────────────
    {
      name: 'Daal Chawal',
      nameUrdu: 'دال چاول',
      description: 'Simple yellow lentil soup served over steamed white rice',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Vegetable Pulao',
      nameUrdu: 'سبزی پلاؤ',
      description: 'Fragrant basmati rice cooked with seasonal vegetables',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Khichdi',
      nameUrdu: 'کھچڑی',
      description: 'Soft rice and lentil porridge — comfort food for all ages',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Standalone | Non-Veg ──────────────────────────────────────────────────
    {
      name: 'Nihari',
      nameUrdu: 'نہاری',
      description: 'Slow cooked beef shank stew — a Mughal era breakfast classic',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 240,
      mealTimes: ['BREAKFAST', 'LUNCH'],
    },
    {
      name: 'Haleem',
      nameUrdu: 'حلیم',
      description: 'Slow cooked wheat, lentils and meat — thick and nutritious',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: true,
      prepTimeMinutes: 180,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Chapli Kebab',
      nameUrdu: 'چپلی کباب',
      description: 'Flat minced chicken patties with tomato and coriander',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'HOT',
      region: 'KPK',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER', 'SNACK'],
    },
    {
      name: 'Beef Seekh Kebab',
      nameUrdu: 'سیخ کباب',
      description: 'Spiced minced beef skewers grilled over charcoal',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 30,
      mealTimes: ['LUNCH', 'DINNER', 'SNACK'],
    },
    {
      name: 'Paye',
      nameUrdu: 'پائے',
      description: 'Slow cooked trotters in a rich spiced broth — Sunday special',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 300,
      mealTimes: ['BREAKFAST'],
    },

    // ── Standalone | Veg ──────────────────────────────────────────────────────
    {
      name: 'Samosa',
      nameUrdu: 'سموسہ',
      description: 'Crispy pastry filled with spiced potato and peas',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Pakora',
      nameUrdu: 'پکوڑہ',
      description: 'Crispy battered and fried vegetables — perfect with chai',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Chana Chaat',
      nameUrdu: 'چنا چاٹ',
      description: 'Tangy chickpea salad with tamarind, onion and coriander',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 15,
      mealTimes: ['SNACK', 'LUNCH'],
    },

    // ── Both | Non-Veg ────────────────────────────────────────────────────────
    {
      name: 'Chicken Korma',
      nameUrdu: 'چکن قورمہ',
      description: 'Rich and creamy chicken curry with yogurt and whole spices',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Both | Veg ────────────────────────────────────────────────────────────
    {
      name: 'Daal Tadka',
      nameUrdu: 'دال تڑکہ',
      description: 'Yellow lentils tempered with cumin, garlic and dried chilli',
      baseType: 'BOTH',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Aloo Ki Sabzi',
      nameUrdu: 'آلو کی سبزی',
      description: 'Simple spiced potato dry curry — quick everyday meal',
      baseType: 'BOTH',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Mix Daal',
      nameUrdu: 'مکس دال',
      description: 'Five lentils slow cooked together with a smoky tarka',
      baseType: 'BOTH',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['LUNCH', 'DINNER'],
    },
  ]

  // Insert all dishes
  let count = 0
  for (const dish of dishes) {
    await prisma.dish.upsert({
      where: { name: dish.name },
      update: {},
      create: dish,
    })
    count++
  }

  console.log(`✅ ${count} dishes seeded`)
  console.log('✅ Stage 1 seed complete')
}

main()
  .catch(e => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })