const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

async function main() {

  // ─── Users ──────────────────────────────────────────────────────────────────
  console.log('🌱 Seeding users...')

  const adminPassword = await bcrypt.hash('admin123', 12)
  const memberPassword = await bcrypt.hash('user123', 12)

  const admin = await prisma.user.upsert({
    where: { email: 'admin@gharkhana.com' },
    update: {},
    create: {
      email: 'admin@gharkhana.com',
      name: 'Super Admin',
      passwordHash: adminPassword,
      role: 'SUPER_ADMIN',
      emailVerified: new Date(),
      onboardedAt: new Date(),
      dietaryType: 'BOTH',
      spiceTolerance: 'HOT',
      healthGoal: 'BALANCED',
    }
  })

  const member = await prisma.user.upsert({
    where: { email: 'test@gharkhana.com' },
    update: {},
    create: {
      email: 'test@gharkhana.com',
      name: 'Test User',
      passwordHash: memberPassword,
      role: 'MEMBER',
      emailVerified: new Date(),
      onboardedAt: new Date(),
      dietaryType: 'NON_VEG',
      spiceTolerance: 'MEDIUM',
      healthGoal: 'BALANCED',
    }
  })

  console.log('✅ Users seeded:', admin.email, member.email)

  // ─── Dishes ─────────────────────────────────────────────────────────────────
  console.log('🌱 Seeding dishes...')

  const dishes = [

    // ── Roti-Based | Non-Veg ──────────────────────────────────────────────────
    {
      name: 'Chicken Karahi',
      nameUrdu: 'چکن کڑاہی',
      description: 'Juicy chicken cooked in a spiced tomato and ginger sauce in a wok',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Mutton Karahi',
      nameUrdu: 'مٹن کڑاہی',
      description: 'Slow cooked mutton in a rich spiced karahi gravy',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Beef Qeema',
      nameUrdu: 'بیف قیمہ',
      description: 'Spiced minced beef cooked with peas and tomatoes',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 30,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Handi',
      nameUrdu: 'چکن ہانڈی',
      description: 'Creamy chicken curry cooked in a clay pot style',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 50,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Saag Gosht',
      nameUrdu: 'ساگ گوشت',
      description: 'Tender mutton cooked with fresh spinach and spices',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 75,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Fish Curry',
      nameUrdu: 'مچھلی کری',
      description: 'Fresh fish cooked in a tangy tamarind and spice gravy',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'FISH',
      spiceLevel: 'HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Aloo Gosht',
      nameUrdu: 'آلو گوشت',
      description: 'Mutton and potato curry — a Pakistani household classic',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 80,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Roti-Based | Veg ──────────────────────────────────────────────────────
    {
      name: 'Daal Makhani',
      nameUrdu: 'دال مکھنی',
      description: 'Slow cooked black lentils in a rich buttery sauce',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Aloo Paratha',
      nameUrdu: 'آلو پراٹھا',
      description: 'Crispy flatbread stuffed with spiced mashed potato',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['BREAKFAST', 'LUNCH'],
    },
    {
      name: 'Paneer Karahi',
      nameUrdu: 'پنیر کڑاہی',
      description: 'Cottage cheese cooked in a spiced tomato karahi sauce',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'PANEER',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 35,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Saag',
      nameUrdu: 'ساگ',
      description: 'Slow cooked mustard greens with butter and makki roti',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Rice-Based | Non-Veg ──────────────────────────────────────────────────
    {
      name: 'Chicken Biryani',
      nameUrdu: 'چکن بریانی',
      description: 'Fragrant basmati rice layered with spiced chicken and saffron',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Mutton Biryani',
      nameUrdu: 'مٹن بریانی',
      description: 'Slow dum-cooked mutton biryani with whole spices',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 120,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Beef Pulao',
      nameUrdu: 'بیف پلاؤ',
      description: 'Fragrant rice cooked with tender beef and whole spices',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Pulao',
      nameUrdu: 'چکن پلاؤ',
      description: 'Light and aromatic rice cooked with chicken and subtle spices',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Egg Fried Rice',
      nameUrdu: 'انڈہ فرائیڈ رائس',
      description: 'Stir fried rice with eggs, vegetables and soy sauce',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'EGG',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Fish Biryani',
      nameUrdu: 'مچھلی بریانی',
      description: 'Tangy and spiced fish layered with aromatic basmati rice',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'FISH',
      spiceLevel: 'HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 75,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Rice-Based | Veg ──────────────────────────────────────────────────────
    {
      name: 'Daal Chawal',
      nameUrdu: 'دال چاول',
      description: 'Simple yellow lentil soup served over steamed white rice',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Vegetable Pulao',
      nameUrdu: 'سبزی پلاؤ',
      description: 'Fragrant basmati rice cooked with seasonal vegetables',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Khichdi',
      nameUrdu: 'کھچڑی',
      description: 'Soft rice and lentil porridge — comfort food for all ages',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Standalone | Non-Veg ──────────────────────────────────────────────────
    {
      name: 'Nihari',
      nameUrdu: 'نہاری',
      description: 'Slow cooked beef shank stew — a Mughal era breakfast classic',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 240,
      mealTimes: ['BREAKFAST', 'LUNCH'],
    },
    {
      name: 'Haleem',
      nameUrdu: 'حلیم',
      description: 'Slow cooked wheat, lentils and meat — thick and nutritious',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: true,
      prepTimeMinutes: 180,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Chapli Kebab',
      nameUrdu: 'چپلی کباب',
      description: 'Flat minced chicken patties with tomato and coriander',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'HOT',
      region: 'KPK',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER', 'SNACK'],
    },
    {
      name: 'Beef Seekh Kebab',
      nameUrdu: 'سیخ کباب',
      description: 'Spiced minced beef skewers grilled over charcoal',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 30,
      mealTimes: ['LUNCH', 'DINNER', 'SNACK'],
    },
    {
      name: 'Paye',
      nameUrdu: 'پائے',
      description: 'Slow cooked trotters in a rich spiced broth — Sunday special',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 300,
      mealTimes: ['BREAKFAST'],
    },

    // ── Standalone | Veg ──────────────────────────────────────────────────────
    {
      name: 'Samosa',
      nameUrdu: 'سموسہ',
      description: 'Crispy pastry filled with spiced potato and peas',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Pakora',
      nameUrdu: 'پکوڑہ',
      description: 'Crispy battered and fried vegetables — perfect with chai',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Chana Chaat',
      nameUrdu: 'چنا چاٹ',
      description: 'Tangy chickpea salad with tamarind, onion and coriander',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 15,
      mealTimes: ['SNACK', 'LUNCH'],
    },

    // ── Both | Non-Veg ────────────────────────────────────────────────────────
    {
      name: 'Chicken Korma',
      nameUrdu: 'چکن قورمہ',
      description: 'Rich and creamy chicken curry with yogurt and whole spices',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── Both | Veg ────────────────────────────────────────────────────────────
    {
      name: 'Daal Tadka',
      nameUrdu: 'دال تڑکہ',
      description: 'Yellow lentils tempered with cumin, garlic and dried chilli',
      baseType: 'BOTH',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Aloo Ki Sabzi',
      nameUrdu: 'آلو کی سبزی',
      description: 'Simple spiced potato dry curry — quick everyday meal',
      baseType: 'BOTH',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Mix Daal',
      nameUrdu: 'مکس دال',
      description: 'Five lentils slow cooked together with a smoky tarka',
      baseType: 'BOTH',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ═════════════════════════════════════════════════════════════════════════════
    // Stage 3 — 70 additional dishes (total: 102)
    // ═════════════════════════════════════════════════════════════════════════════

    // ── ROTI_BASED (20 new) ─────────────────────────────────────────────────────

    {
      name: 'Mutton Korma',
      nameUrdu: 'مٹن قورمہ',
      description: 'Rich mutton curry with yogurt, fried onions and aromatic whole spices',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Karahi Gosht',
      nameUrdu: 'کڑاہی گوشت',
      description: 'Mutton cooked in a wok with tomatoes, green chillies and fresh ginger',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'HOT',
      region: 'KPK',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Machli Karahi',
      nameUrdu: 'مچھلی کڑاہی',
      description: 'Fresh fish cooked in a spiced tomato karahi with coriander',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'FISH',
      spiceLevel: 'HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 35,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Palak Paneer',
      nameUrdu: 'پالک پنیر',
      description: 'Cottage cheese cubes in a creamy spinach gravy',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'PANEER',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 35,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Baingan Bharta',
      nameUrdu: 'بینگن بھرتا',
      description: 'Smoky roasted eggplant mashed with onions, tomatoes and spices',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'NONE',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Aloo Palak',
      nameUrdu: 'آلو پالک',
      description: 'Potatoes cooked with fresh spinach and cumin',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chana Masala',
      nameUrdu: 'چنا مصالحہ',
      description: 'Chickpeas cooked in a tangy spiced tomato gravy',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Keema Paratha',
      nameUrdu: 'قیمہ پراٹھا',
      description: 'Crispy flatbread stuffed with spiced minced meat',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 35,
      mealTimes: ['BREAKFAST', 'LUNCH'],
    },
    {
      name: 'Bhindi Masala',
      nameUrdu: 'بھنڈی مصالحہ',
      description: 'Okra stir fried with onions, tomatoes and spices',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'NONE',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Gobhi Aloo',
      nameUrdu: 'گوبھی آلو',
      description: 'Cauliflower and potatoes cooked dry with turmeric and cumin',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Tawa Chicken',
      nameUrdu: 'توا چکن',
      description: 'Chicken cooked on a flat griddle with spices and capsicum',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Namkeen Gosht',
      nameUrdu: 'نمکین گوشت',
      description: 'Simple salt and pepper mutton — Peshawari home style',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Achari Chicken',
      nameUrdu: 'اچاری چکن',
      description: 'Chicken cooked in tangy pickle spices and mustard oil',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Kadhi Pakora',
      nameUrdu: 'کڑھی پکوڑا',
      description: 'Gram flour fritters in a tangy yogurt and turmeric curry',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Masoor Daal',
      nameUrdu: 'مسور دال',
      description: 'Red lentils cooked to a smooth consistency with cumin tarka',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Beef Nihari Nalli',
      nameUrdu: 'بیف نالی نہاری',
      description: 'Rich bone marrow stew slow cooked overnight with ground spices',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 300,
      mealTimes: ['BREAKFAST'],
    },
    {
      name: 'Methi Thepla',
      nameUrdu: 'میتھی تھیپلا',
      description: 'Fenugreek spiced flatbread — healthy Gujarati snack popular across South Asia',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['BREAKFAST', 'SNACK'],
    },
    {
      name: 'Chicken White Karahi',
      nameUrdu: 'وائٹ کڑاہی',
      description: 'Cream based chicken karahi without tomato — rich and mild',
      baseType: 'ROTI_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 50,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Maash Ki Daal',
      nameUrdu: 'ماش کی دال',
      description: 'Black gram lentils cooked with ginger and simple tarka — KPK staple',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Tarka Moong Daal',
      nameUrdu: 'ترکا مونگ دال',
      description: 'Split moong lentils tempered with garlic, cumin and dried chillies',
      baseType: 'ROTI_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── RICE_BASED (20 new) ─────────────────────────────────────────────────────

    {
      name: 'Sindhi Biryani',
      nameUrdu: 'سندھی بریانی',
      description: 'Fiery Sindhi style biryani with potatoes, plums and extra spice',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'EXTRA_HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 120,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Hyderabadi Biryani',
      nameUrdu: 'حیدرآبادی بریانی',
      description: 'Layered dum biryani with saffron, mint and caramelized onions',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MEDIUM',
      region: 'Hyderabad',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 100,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Memoni Biryani',
      nameUrdu: 'میمنی بریانی',
      description: 'Memon community style biryani with whole spices and potatoes',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 120,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Prawn Biryani',
      nameUrdu: 'جھینگا بریانی',
      description: 'Coastal biryani with marinated prawns and fragrant rice',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'FISH',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 75,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Kabuli Pulao',
      nameUrdu: 'کابلی پلاؤ',
      description: 'Afghani style pulao with raisins, carrots and lamb',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Matar Pulao',
      nameUrdu: 'مٹر پلاؤ',
      description: 'Simple peas pulao — everyday aromatic rice with green peas',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Moong Daal Khichdi',
      nameUrdu: 'مونگ دال کھچڑی',
      description: 'Soft rice with moong lentils — gentle comfort food for the sick and elderly',
      baseType: 'RICE_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Sabudana Khichdi',
      nameUrdu: 'ساگودانہ کھچڑی',
      description: 'Tapioca pearls stir fried with peanuts, cumin and green chillies',
      baseType: 'RICE_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Bengal',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['BREAKFAST', 'SNACK'],
    },
    {
      name: 'Beef Biryani',
      nameUrdu: 'بیف بریانی',
      description: 'Slow cooked beef layered with spiced basmati rice and fried onions',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'HOT',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 120,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Tahiri',
      nameUrdu: 'تہری',
      description: 'Spiced vegetable rice cooked one-pot with potatoes and peas',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Egg Biryani',
      nameUrdu: 'انڈہ بریانی',
      description: 'Budget-friendly biryani with boiled eggs and aromatic rice',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'EGG',
      spiceLevel: 'MEDIUM',
      region: 'Hyderabad',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Bengali Khichuri',
      nameUrdu: 'بنگالی کھچوری',
      description: 'Bengali comfort rice and lentils cooked with vegetables and ghee',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Bengal',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 35,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Tikka Biryani',
      nameUrdu: 'چکن ٹکہ بریانی',
      description: 'Grilled chicken tikka pieces layered with spiced rice',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Zarda',
      nameUrdu: 'زردہ',
      description: 'Sweet saffron rice with nuts, raisins and cardamom — festive dessert rice',
      baseType: 'RICE_BASED',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 45,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Yakhni Pulao',
      nameUrdu: 'یخنی پلاؤ',
      description: 'Aromatic rice cooked in a clear meat broth with whole spices',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Kichri Daal',
      nameUrdu: 'کچری دال',
      description: 'Sindhi style rice and chana daal cooked together with turmeric',
      baseType: 'RICE_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Sindh',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Bengali Fish Bhuna Khichuri',
      nameUrdu: 'بنگالی مچھلی بھونا کھچوری',
      description: 'Bengali khichuri served with pan-fried spiced fish — rainy day classic',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'FISH',
      spiceLevel: 'MEDIUM',
      region: 'Bengal',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 50,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Mutton Yakhni Pulao',
      nameUrdu: 'مٹن یخنی پلاؤ',
      description: 'Fragrant rice cooked in mutton bone broth — Peshawari specialty',
      baseType: 'RICE_BASED',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 90,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chana Pulao',
      nameUrdu: 'چنا پلاؤ',
      description: 'Chickpea pulao with cumin and whole spices — simple one-pot meal',
      baseType: 'RICE_BASED',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── BOTH (15 new) ───────────────────────────────────────────────────────────

    {
      name: 'Poori Cholay',
      nameUrdu: 'پوری چھولے',
      description: 'Deep fried puffed bread served with spiced chickpea curry',
      baseType: 'BOTH',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['BREAKFAST', 'LUNCH'],
    },
    {
      name: 'Anda Curry',
      nameUrdu: 'انڈا کری',
      description: 'Boiled eggs in a spiced onion-tomato gravy — quick weeknight dinner',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'EGG',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Aloo Qeema',
      nameUrdu: 'آلو قیمہ',
      description: 'Minced meat with potatoes — everyday comfort curry',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 30,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Sindhi Daal',
      nameUrdu: 'سندھی دال',
      description: 'Tangy Sindhi style chana daal with tamarind and kokum',
      baseType: 'BOTH',
      dietaryType: 'VEGAN',
      proteinType: 'LENTIL',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Shaljam Gosht',
      nameUrdu: 'شلجم گوشت',
      description: 'Mutton cooked with turnips — a desi winter classic',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 75,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Bengali Chicken Curry',
      nameUrdu: 'بنگالی چکن کری',
      description: 'Bengali style chicken with mustard oil, potatoes and warm spices',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MEDIUM',
      region: 'Bengal',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 50,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Bengali Fish Curry',
      nameUrdu: 'بنگالی مچھلی کری',
      description: 'Mustard based fish curry with turmeric — everyday Bengali favourite',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'FISH',
      spiceLevel: 'MEDIUM',
      region: 'Bengal',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 35,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Bengali Egg Curry',
      nameUrdu: 'بنگالی انڈا کری',
      description: 'Eggs in a light onion and tomato gravy with panch phoron spices',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'EGG',
      spiceLevel: 'MILD',
      region: 'Bengal',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Hyderabadi Dalcha',
      nameUrdu: 'حیدرآبادی دالچہ',
      description: 'Chana daal cooked with mutton and tamarind — Hyderabadi specialty',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'HOT',
      region: 'Hyderabad',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 75,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Changezi',
      nameUrdu: 'چکن چنگیزی',
      description: 'Mughlai style chicken in a red onion and tomato gravy',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MEDIUM',
      region: 'Hyderabad',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 50,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Palak Gosht',
      nameUrdu: 'پالک گوشت',
      description: 'Beef cooked with spinach puree — iron-rich winter meal',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MEDIUM',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Tinda Gosht',
      nameUrdu: 'ٹنڈا گوشت',
      description: 'Apple gourd cooked with mutton — light summer curry',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 60,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Bhuna Gosht',
      nameUrdu: 'بھونا گوشت',
      description: 'Dry roasted mutton with minimal gravy — rich and caramelized',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'HOT',
      region: 'KPK',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 75,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Sabzi Khorma',
      nameUrdu: 'سبزی کھورمہ',
      description: 'Mixed vegetables in a creamy yogurt sauce with mild spices',
      baseType: 'BOTH',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Hyderabad',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Lauki Gosht',
      nameUrdu: 'لوکی گوشت',
      description: 'Bottle gourd cooked with meat — light and easy to digest',
      baseType: 'BOTH',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 50,
      mealTimes: ['LUNCH', 'DINNER'],
    },

    // ── STANDALONE (15 new) ─────────────────────────────────────────────────────

    {
      name: 'Sheer Khurma',
      nameUrdu: 'شیر خرمہ',
      description: 'Vermicelli pudding with milk, dates, pistachios — essential Eid dessert',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Hyderabad',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 40,
      mealTimes: ['BREAKFAST', 'SNACK'],
    },
    {
      name: 'Kheer',
      nameUrdu: 'کھیر',
      description: 'Classic rice pudding slow cooked in milk with cardamom and nuts',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 45,
      mealTimes: ['DINNER', 'SNACK'],
    },
    {
      name: 'Sooji Halwa',
      nameUrdu: 'سوجی حلوہ',
      description: 'Semolina pudding fried in ghee with sugar, nuts and cardamom',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 15,
      mealTimes: ['BREAKFAST', 'SNACK'],
    },
    {
      name: 'Gajar Halwa',
      nameUrdu: 'گاجر حلوہ',
      description: 'Grated carrots slow cooked in milk and sugar — winter favourite',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 60,
      mealTimes: ['DINNER', 'SNACK'],
    },
    {
      name: 'Sajji',
      nameUrdu: 'سجی',
      description: 'Whole marinated lamb leg slow roasted over coals — Balochi specialty',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'MUTTON',
      spiceLevel: 'MILD',
      region: 'KPK',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 180,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Dahi Bhalle',
      nameUrdu: 'دہی بھلے',
      description: 'Lentil fritters soaked in yogurt with tamarind and mint chutney',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'LENTIL',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 45,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Dahi Puri',
      nameUrdu: 'دہی پوری',
      description: 'Crispy hollow puris filled with yogurt, chutney and chickpeas',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MEDIUM',
      region: 'Sindh',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 20,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Lassi',
      nameUrdu: 'لسی',
      description: 'Chilled yogurt drink blended with sugar or salt — Punjabi classic',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 5,
      mealTimes: ['BREAKFAST', 'LUNCH', 'SNACK'],
    },
    {
      name: 'Raita',
      nameUrdu: 'رائتہ',
      description: 'Yogurt mixed with cucumber, onions and spices — served as a side',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: true,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 5,
      mealTimes: ['LUNCH', 'DINNER'],
    },
    {
      name: 'Chicken Tikka',
      nameUrdu: 'چکن ٹکہ',
      description: 'Charcoal grilled marinated chicken pieces — smoky and juicy',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 40,
      mealTimes: ['LUNCH', 'DINNER', 'SNACK'],
    },
    {
      name: 'Gol Gappay',
      nameUrdu: 'گول گپے',
      description: 'Crispy hollow shells with spiced tamarind water — street food king',
      baseType: 'STANDALONE',
      dietaryType: 'VEGAN',
      proteinType: 'NONE',
      spiceLevel: 'HOT',
      region: 'Punjab',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 15,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Bengali Mishti Doi',
      nameUrdu: 'بنگالی مشتی دوئی',
      description: 'Sweetened fermented yogurt set in clay pots — Bengali dessert',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Bengal',
      isQuick: false,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 30,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Bengali Rasgulla',
      nameUrdu: 'بنگالی رسگلا',
      description: 'Soft cottage cheese balls soaked in sugar syrup — classic Bengali sweet',
      baseType: 'STANDALONE',
      dietaryType: 'VEG',
      proteinType: 'NONE',
      spiceLevel: 'MILD',
      region: 'Bengal',
      isQuick: false,
      isHealthy: false,
      isFestive: true,
      prepTimeMinutes: 45,
      mealTimes: ['SNACK'],
    },
    {
      name: 'Peshawari Chapli Kebab',
      nameUrdu: 'پشاوری چپلی کباب',
      description: 'Flat beef patties with pomegranate seeds and coriander — KPK iconic',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'BEEF',
      spiceLevel: 'HOT',
      region: 'KPK',
      isQuick: true,
      isHealthy: false,
      isFestive: false,
      prepTimeMinutes: 25,
      mealTimes: ['LUNCH', 'DINNER', 'SNACK'],
    },
    {
      name: 'Malai Boti',
      nameUrdu: 'ملائی بوٹی',
      description: 'Cream marinated chicken grilled tender — mild and creamy',
      baseType: 'STANDALONE',
      dietaryType: 'NON_VEG',
      proteinType: 'CHICKEN',
      spiceLevel: 'MILD',
      region: 'Punjab',
      isQuick: false,
      isHealthy: true,
      isFestive: false,
      prepTimeMinutes: 35,
      mealTimes: ['LUNCH', 'DINNER', 'SNACK'],
    },
  ]

  // Insert all dishes
  let count = 0
  for (const dish of dishes) {
    await prisma.dish.upsert({
      where: { name: dish.name },
      update: {},
      create: dish,
    })
    count++
  }

  console.log(`✅ ${count} dishes seeded`)
  console.log('✅ Stage 1 seed complete')
}

main()
  .catch(e => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })